#!/bin/bash
ENV_FILE=./.env

[ -f $ENV_FILE ] && . $ENV_FILE

[ -z $MONGO_VERSION ] && echo Please set a MONGO_VERSION environment variable && exit
[ -z $DOCKER_HUB_ORG ] && echo Please set a DOCKER_HUB_ORG environment variable && exit

docker_tag=${DOCKER_HUB_ORG}/rocket-ready-mongo:${MONGO_VERSION}

docker build --build-arg="MONGO_VERSION=${MONGO_VERSION}" --tag ${docker_tag} server
docker push ${docker_tag}

docker build --build-arg="MONGO_VERSION=${MONGO_VERSION}" --tag ${docker_tag}-setup setup
docker push ${docker_tag}-setup

